### ISSUE TITLE
How do we update services with new versions?

### ISSUE THREAD

**Issue by AndrewBarba** [aws-ia/cloudformation-fastly-resource-providers#53]
I'm currently trying to use this in [SST](https://sst.dev) which is a wrapper around CDK. I'm able to create the initial service, backend and domain on first deploy but then a bunch of issues crop up:

1. On initial deploy there is no way to activate the version
2. On subsequent updates, everything fails because nothing creates a new version and keeps trying to edit the `attrLatestVersionId`

Is it even possible to use this in its current state? My guess is we need to add a `Fastly::Services::Version` construct, or any update to an underlying service `Fastly::Services::***` needs to know to create a new version first and set it as the latest version. Additionally, we need some way to then activate the latest version once all changes are reconciled and added to the new version

**Comment by AndrewBarba** [comment]
Excellent @CloudChoom thanks a lot. And while I have you here, some other key ones I need:

- [VCL Objects](https://developer.fastly.com/reference/api/vcl-services/) like HTTP3, Gzip, etc.
- [VCL Snippets](https://developer.fastly.com/reference/api/vcl-services/snippet/)
- [Products](https://developer.fastly.com/reference/api/products/enablement/)

**Comment by CloudChoom** [comment]
Thanks @AndrewBarba We'll have a look at those as well. Working with the team to get an estimate on each of those. Out of curiosity, are there other 3rd party providers you're looking to use other than Fastly?

**Comment by AndrewBarba** [comment]
My favorite backend stack:
- DNS - Cloudflare
- CDN - Fastly
- Storage/Compute/Queues - AWS
- Database - PlanetScale or MongoDB Atlas
- Logging - Axiom or BetterStack

**Comment by CloudChoom** [comment]
FYI in case you haven't already seen, we do have CFN resources available for Cloudflare and MongoDB Atlas as well.

https://github.com/aws-ia/cloudformation-cloudflare-resource-providers
https://www.mongodb.com/developer/code-examples/bash/get-started-atlas-aws-cloudformation/

**Comment by AndrewBarba** [comment]
Awesome that's great to hear. And if you look at the other resources I asked for they all rely on a version so I think the version resource sets us up nicely for everything after. 

And yes activating the version seemed tricky, I wasn't sure how that plays with the CF model / what special case would be needed for that.

**Comment by CloudChoom** [comment]
For my knowledge, if we don't have a good way to automate the activation, the version resource type will still be useful for your use case, right?

**Comment by AndrewBarba** [comment]
Activating the version is definitely critical, but I won't stop you from working on the Version resource. Wondering if we could actually have an `Fastly::Services::ActivateVersion` resource thats basically always the last thing defined and fully controls activating the version. This would also make activation opt in and give people more control if for some reason they dont want to activate a version right away

**Comment by CloudChoom** [comment]
Discussed with the team and we're planning to add both a Version and ActiveVersion resource. The ActiveVersion resource will behave how you described, it will deactivate the existing resource and activate a new version. Also we deviated from calling it ActivateVersion and will call it ActiveVersion because we typically name resource types as nouns instead of verbs.

Development on both of these will start soon. I'll provide more updates here.

**Comment by CloudChoom** [comment]
We're happy to announce Fastly::Service::ActiveVersion and Fastly::Service::Version resources are now available for use in the Registry! Please give it a try and let us know if anyone has any feedback.

We'll go ahead and close this issue.

**Comment by AndrewBarba** [comment]
Awesome thank you. Do you have docs on using those as well?

**Comment by CloudChoom** [comment]
Here you go:

https://github.com/aws-ia/cloudformation-fastly-resource-providers/tree/main/Fastly-Services-ActiveVersion/docs/README.md
https://github.com/aws-ia/cloudformation-fastly-resource-providers/blob/main/Fastly-Services-Version/docs/README.md

**Comment by AndrewBarba** [comment]
Yup just read these, makes sense! Will test these out and open new issue if needed. Thanks a ton

**Comment by CloudChoom** [comment]
The team is looking into this and planning the fix as we speak.

**Comment by CloudChoom** [comment]
@AndrewBarba the versionId type mistmatch issue should be resolved now for the other resources.
